//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceAlmacen1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/WS_Almacen1.Models")]
    public partial class Producto : object
    {
        
        private string NombreProductoField;
        
        private string NumeroProductoField;
        
        private decimal PrecioField;
        
        private string TipoTransaccionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProducto
        {
            get
            {
                return this.NombreProductoField;
            }
            set
            {
                this.NombreProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroProducto
        {
            get
            {
                return this.NumeroProductoField;
            }
            set
            {
                this.NumeroProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio
        {
            get
            {
                return this.PrecioField;
            }
            set
            {
                this.PrecioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTransaccion
        {
            get
            {
                return this.TipoTransaccionField;
            }
            set
            {
                this.TipoTransaccionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaManProducto", Namespace="http://schemas.datacontract.org/2004/07/WS_Almacen1.Models")]
    public partial class RespuestaManProducto : object
    {
        
        private string MensajeField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAlmacen1.IWS_Almacen1")]
    public interface IWS_Almacen1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_Almacen1/MantenerProducto", ReplyAction="http://tempuri.org/IWS_Almacen1/MantenerProductoResponse")]
        System.Threading.Tasks.Task<ServiceReferenceAlmacen1.RespuestaManProducto> MantenerProductoAsync(ServiceReferenceAlmacen1.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_Almacen1/ObtenerProductos", ReplyAction="http://tempuri.org/IWS_Almacen1/ObtenerProductosResponse")]
        System.Threading.Tasks.Task<ServiceReferenceAlmacen1.Producto[]> ObtenerProductosAsync(string filtro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IWS_Almacen1Channel : ServiceReferenceAlmacen1.IWS_Almacen1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WS_Almacen1Client : System.ServiceModel.ClientBase<ServiceReferenceAlmacen1.IWS_Almacen1>, ServiceReferenceAlmacen1.IWS_Almacen1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WS_Almacen1Client() : 
                base(WS_Almacen1Client.GetDefaultBinding(), WS_Almacen1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWS_Almacen1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_Almacen1Client(EndpointConfiguration endpointConfiguration) : 
                base(WS_Almacen1Client.GetBindingForEndpoint(endpointConfiguration), WS_Almacen1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_Almacen1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WS_Almacen1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_Almacen1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WS_Almacen1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_Almacen1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAlmacen1.RespuestaManProducto> MantenerProductoAsync(ServiceReferenceAlmacen1.Producto producto)
        {
            return base.Channel.MantenerProductoAsync(producto);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAlmacen1.Producto[]> ObtenerProductosAsync(string filtro)
        {
            return base.Channel.ObtenerProductosAsync(filtro);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWS_Almacen1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWS_Almacen1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8089/WS_Almacen1.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WS_Almacen1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWS_Almacen1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WS_Almacen1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWS_Almacen1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWS_Almacen1,
        }
    }
}
