//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceVerificador
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteInfo", Namespace="http://schemas.datacontract.org/2004/07/WS_VERIFICADOR1y2")]
    public partial class ClienteInfo : object
    {
        
        private string Apellido1Field;
        
        private string Apellido2Field;
        
        private string CorreoField;
        
        private string DireccionField;
        
        private string IdField;
        
        private string NombreField;
        
        private string PaisField;
        
        private string TelefonoField;
        
        private string TransaccionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido1
        {
            get
            {
                return this.Apellido1Field;
            }
            set
            {
                this.Apellido1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido2
        {
            get
            {
                return this.Apellido2Field;
            }
            set
            {
                this.Apellido2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pais
        {
            get
            {
                return this.PaisField;
            }
            set
            {
                this.PaisField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Transaccion
        {
            get
            {
                return this.TransaccionField;
            }
            set
            {
                this.TransaccionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicio", Namespace="http://schemas.datacontract.org/2004/07/WS_VERIFICADOR1y2")]
    public partial class RespuestaServicio : object
    {
        
        private string MensajeField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompraInfo", Namespace="http://schemas.datacontract.org/2004/07/WS_VERIFICADOR1y2")]
    public partial class CompraInfo : object
    {
        
        private string CodigoVerificacionField;
        
        private string FechaCompraField;
        
        private string FechaVencimientoField;
        
        private string IdClienteField;
        
        private string NumeroCompraField;
        
        private string NumeroTarjetaField;
        
        private ServiceReferenceVerificador.ProductoInfo[] ProductosField;
        
        private string TotalCompraField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoVerificacion
        {
            get
            {
                return this.CodigoVerificacionField;
            }
            set
            {
                this.CodigoVerificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCompra
        {
            get
            {
                return this.FechaCompraField;
            }
            set
            {
                this.FechaCompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaVencimiento
        {
            get
            {
                return this.FechaVencimientoField;
            }
            set
            {
                this.FechaVencimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCliente
        {
            get
            {
                return this.IdClienteField;
            }
            set
            {
                this.IdClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCompra
        {
            get
            {
                return this.NumeroCompraField;
            }
            set
            {
                this.NumeroCompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroTarjeta
        {
            get
            {
                return this.NumeroTarjetaField;
            }
            set
            {
                this.NumeroTarjetaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceVerificador.ProductoInfo[] Productos
        {
            get
            {
                return this.ProductosField;
            }
            set
            {
                this.ProductosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalCompra
        {
            get
            {
                return this.TotalCompraField;
            }
            set
            {
                this.TotalCompraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoInfo", Namespace="http://schemas.datacontract.org/2004/07/WS_VERIFICADOR1y2")]
    public partial class ProductoInfo : object
    {
        
        private string CantidadField;
        
        private string CodigoProductoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoProducto
        {
            get
            {
                return this.CodigoProductoField;
            }
            set
            {
                this.CodigoProductoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceVerificador.IVerificadorService")]
    public interface IVerificadorService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerificadorService/GestionarCliente", ReplyAction="http://tempuri.org/IVerificadorService/GestionarClienteResponse")]
        System.Threading.Tasks.Task<ServiceReferenceVerificador.RespuestaServicio> GestionarClienteAsync(ServiceReferenceVerificador.ClienteInfo cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVerificadorService/GestionarCompra", ReplyAction="http://tempuri.org/IVerificadorService/GestionarCompraResponse")]
        System.Threading.Tasks.Task<ServiceReferenceVerificador.RespuestaServicio> GestionarCompraAsync(ServiceReferenceVerificador.CompraInfo compra);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IVerificadorServiceChannel : ServiceReferenceVerificador.IVerificadorService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class VerificadorServiceClient : System.ServiceModel.ClientBase<ServiceReferenceVerificador.IVerificadorService>, ServiceReferenceVerificador.IVerificadorService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VerificadorServiceClient() : 
                base(VerificadorServiceClient.GetDefaultBinding(), VerificadorServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IVerificadorService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VerificadorServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(VerificadorServiceClient.GetBindingForEndpoint(endpointConfiguration), VerificadorServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VerificadorServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VerificadorServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VerificadorServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VerificadorServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VerificadorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceVerificador.RespuestaServicio> GestionarClienteAsync(ServiceReferenceVerificador.ClienteInfo cliente)
        {
            return base.Channel.GestionarClienteAsync(cliente);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceVerificador.RespuestaServicio> GestionarCompraAsync(ServiceReferenceVerificador.CompraInfo compra)
        {
            return base.Channel.GestionarCompraAsync(compra);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVerificadorService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVerificadorService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8090/VerificadorService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return VerificadorServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IVerificadorService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return VerificadorServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IVerificadorService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IVerificadorService,
        }
    }
}
