//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudLogin", Namespace="http://schemas.datacontract.org/2004/07/WS_Autenticacion")]
    public partial class SolicitudLogin : object
    {
        
        private string ContrasenaCifradaField;
        
        private int TipoUsuarioField;
        
        private string UsuarioCifradoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContrasenaCifrada
        {
            get
            {
                return this.ContrasenaCifradaField;
            }
            set
            {
                this.ContrasenaCifradaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoUsuario
        {
            get
            {
                return this.TipoUsuarioField;
            }
            set
            {
                this.TipoUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioCifrado
        {
            get
            {
                return this.UsuarioCifradoField;
            }
            set
            {
                this.UsuarioCifradoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaLogin", Namespace="http://schemas.datacontract.org/2004/07/WS_Autenticacion")]
    public partial class RespuestaLogin : object
    {
        
        private string IdField;
        
        private string MensajeField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudRegistro", Namespace="http://schemas.datacontract.org/2004/07/WS_Autenticacion")]
    public partial class SolicitudRegistro : object
    {
        
        private string ContrasenaCifradaField;
        
        private string CorreoField;
        
        private string EstadoField;
        
        private string IdentificacionField;
        
        private string NombreField;
        
        private string PrimerApellidoField;
        
        private string SegundoApellidoField;
        
        private int TipoField;
        
        private string UsuarioCifradoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContrasenaCifrada
        {
            get
            {
                return this.ContrasenaCifradaField;
            }
            set
            {
                this.ContrasenaCifradaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion
        {
            get
            {
                return this.IdentificacionField;
            }
            set
            {
                this.IdentificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioCifrado
        {
            get
            {
                return this.UsuarioCifradoField;
            }
            set
            {
                this.UsuarioCifradoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicio", Namespace="http://schemas.datacontract.org/2004/07/WS_Autenticacion")]
    public partial class RespuestaServicio : object
    {
        
        private string MensajeField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudModificacion", Namespace="http://schemas.datacontract.org/2004/07/WS_Autenticacion")]
    public partial class SolicitudModificacion : object
    {
        
        private string ContrasenaCifradaField;
        
        private string CorreoField;
        
        private string IdentificacionField;
        
        private string NombreField;
        
        private string PrimerApellidoField;
        
        private string SegundoApellidoField;
        
        private string UsuarioCifradoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContrasenaCifrada
        {
            get
            {
                return this.ContrasenaCifradaField;
            }
            set
            {
                this.ContrasenaCifradaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion
        {
            get
            {
                return this.IdentificacionField;
            }
            set
            {
                this.IdentificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioCifrado
        {
            get
            {
                return this.UsuarioCifradoField;
            }
            set
            {
                this.UsuarioCifradoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolicitudCambiarEstado", Namespace="http://schemas.datacontract.org/2004/07/WS_Autenticacion")]
    public partial class SolicitudCambiarEstado : object
    {
        
        private string IdentificacionField;
        
        private string NuevoEstadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion
        {
            get
            {
                return this.IdentificacionField;
            }
            set
            {
                this.IdentificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NuevoEstado
        {
            get
            {
                return this.NuevoEstadoField;
            }
            set
            {
                this.NuevoEstadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListarUsuarios", Namespace="http://schemas.datacontract.org/2004/07/WS_Autenticacion")]
    public partial class ListarUsuarios : object
    {
        
        private string ContrasenaCifradaField;
        
        private string CorreoField;
        
        private string EstadoField;
        
        private string IdentificacionField;
        
        private string NombreField;
        
        private string PrimerApellidoField;
        
        private string SegundoApellidoField;
        
        private int TipoField;
        
        private string UsuarioCifradoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContrasenaCifrada
        {
            get
            {
                return this.ContrasenaCifradaField;
            }
            set
            {
                this.ContrasenaCifradaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion
        {
            get
            {
                return this.IdentificacionField;
            }
            set
            {
                this.IdentificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimerApellido
        {
            get
            {
                return this.PrimerApellidoField;
            }
            set
            {
                this.PrimerApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegundoApellido
        {
            get
            {
                return this.SegundoApellidoField;
            }
            set
            {
                this.SegundoApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tipo
        {
            get
            {
                return this.TipoField;
            }
            set
            {
                this.TipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuarioCifrado
        {
            get
            {
                return this.UsuarioCifradoField;
            }
            set
            {
                this.UsuarioCifradoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAutenticacionService")]
    public interface IAutenticacionService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/AutenticarUsuario", ReplyAction="http://tempuri.org/IAutenticacionService/AutenticarUsuarioResponse")]
        System.Threading.Tasks.Task<ServiceReference1.RespuestaLogin> AutenticarUsuarioAsync(ServiceReference1.SolicitudLogin solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/RegistrarUsuario", ReplyAction="http://tempuri.org/IAutenticacionService/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<ServiceReference1.RespuestaServicio> RegistrarUsuarioAsync(ServiceReference1.SolicitudRegistro solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/ModificarUsuario", ReplyAction="http://tempuri.org/IAutenticacionService/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<ServiceReference1.RespuestaServicio> ModificarUsuarioAsync(ServiceReference1.SolicitudModificacion solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/CambiarEstadoUsuario", ReplyAction="http://tempuri.org/IAutenticacionService/CambiarEstadoUsuarioResponse")]
        System.Threading.Tasks.Task<ServiceReference1.RespuestaServicio> CambiarEstadoUsuarioAsync(ServiceReference1.SolicitudCambiarEstado solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutenticacionService/ObtenerUsuarios", ReplyAction="http://tempuri.org/IAutenticacionService/ObtenerUsuariosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.ListarUsuarios[]> ObtenerUsuariosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IAutenticacionServiceChannel : ServiceReference1.IAutenticacionService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AutenticacionServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IAutenticacionService>, ServiceReference1.IAutenticacionService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AutenticacionServiceClient() : 
                base(AutenticacionServiceClient.GetDefaultBinding(), AutenticacionServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAutenticacionService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AutenticacionServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AutenticacionServiceClient.GetBindingForEndpoint(endpointConfiguration), AutenticacionServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AutenticacionServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AutenticacionServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AutenticacionServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AutenticacionServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AutenticacionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RespuestaLogin> AutenticarUsuarioAsync(ServiceReference1.SolicitudLogin solicitud)
        {
            return base.Channel.AutenticarUsuarioAsync(solicitud);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RespuestaServicio> RegistrarUsuarioAsync(ServiceReference1.SolicitudRegistro solicitud)
        {
            return base.Channel.RegistrarUsuarioAsync(solicitud);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RespuestaServicio> ModificarUsuarioAsync(ServiceReference1.SolicitudModificacion solicitud)
        {
            return base.Channel.ModificarUsuarioAsync(solicitud);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RespuestaServicio> CambiarEstadoUsuarioAsync(ServiceReference1.SolicitudCambiarEstado solicitud)
        {
            return base.Channel.CambiarEstadoUsuarioAsync(solicitud);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ListarUsuarios[]> ObtenerUsuariosAsync()
        {
            return base.Channel.ObtenerUsuariosAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAutenticacionService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAutenticacionService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8091/AutenticacionService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AutenticacionServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAutenticacionService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AutenticacionServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAutenticacionService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAutenticacionService,
        }
    }
}
