//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceAlmacen3
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompraInfo", Namespace="http://schemas.datacontract.org/2004/07/WS_Almacen3.Models")]
    public partial class CompraInfo : object
    {
        
        private string cedulaJuridicaField;
        
        private System.DateTime fechaCompraField;
        
        private ServiceReferenceAlmacen3.ProductoCompra[] listaProductosField;
        
        private string numeroIngresoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cedulaJuridica
        {
            get
            {
                return this.cedulaJuridicaField;
            }
            set
            {
                this.cedulaJuridicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaCompra
        {
            get
            {
                return this.fechaCompraField;
            }
            set
            {
                this.fechaCompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceAlmacen3.ProductoCompra[] listaProductos
        {
            get
            {
                return this.listaProductosField;
            }
            set
            {
                this.listaProductosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroIngreso
        {
            get
            {
                return this.numeroIngresoField;
            }
            set
            {
                this.numeroIngresoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoCompra", Namespace="http://schemas.datacontract.org/2004/07/WS_Almacen3.Models")]
    public partial class ProductoCompra : object
    {
        
        private int CantidadField;
        
        private string NoProductoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoProducto
        {
            get
            {
                return this.NoProductoField;
            }
            set
            {
                this.NoProductoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaCompra", Namespace="http://schemas.datacontract.org/2004/07/WS_Almacen3.Models")]
    public partial class RespuestaCompra : object
    {
        
        private string MensajeField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="_10UltimasCompras", Namespace="http://schemas.datacontract.org/2004/07/WS_Almacen.Models")]
    public partial class _10UltimasCompras : object
    {
        
        private string cedulaJuridicaField;
        
        private string fechaCompraField;
        
        private string nombreField;
        
        private string numeroIngresoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cedulaJuridica
        {
            get
            {
                return this.cedulaJuridicaField;
            }
            set
            {
                this.cedulaJuridicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaCompra
        {
            get
            {
                return this.fechaCompraField;
            }
            set
            {
                this.fechaCompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroIngreso
        {
            get
            {
                return this.numeroIngresoField;
            }
            set
            {
                this.numeroIngresoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleCompra", Namespace="http://schemas.datacontract.org/2004/07/WS_Almacen.Models")]
    public partial class DetalleCompra : object
    {
        
        private ServiceReferenceAlmacen3.ProductoEntrada[] ProductosField;
        
        private int cantidadField;
        
        private string cedulaJuridicaField;
        
        private string fechaCompraField;
        
        private string noProductoField;
        
        private string nombreProductoField;
        
        private string nombreProveedorField;
        
        private string numeroIngresoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceAlmacen3.ProductoEntrada[] Productos
        {
            get
            {
                return this.ProductosField;
            }
            set
            {
                this.ProductosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cedulaJuridica
        {
            get
            {
                return this.cedulaJuridicaField;
            }
            set
            {
                this.cedulaJuridicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fechaCompra
        {
            get
            {
                return this.fechaCompraField;
            }
            set
            {
                this.fechaCompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string noProducto
        {
            get
            {
                return this.noProductoField;
            }
            set
            {
                this.noProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreProducto
        {
            get
            {
                return this.nombreProductoField;
            }
            set
            {
                this.nombreProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreProveedor
        {
            get
            {
                return this.nombreProveedorField;
            }
            set
            {
                this.nombreProveedorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numeroIngreso
        {
            get
            {
                return this.numeroIngresoField;
            }
            set
            {
                this.numeroIngresoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoEntrada", Namespace="http://schemas.datacontract.org/2004/07/WS_Almacen.Models")]
    public partial class ProductoEntrada : object
    {
        
        private int cantidadField;
        
        private string noProductoField;
        
        private string nombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string noProducto
        {
            get
            {
                return this.noProductoField;
            }
            set
            {
                this.noProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAlmacen3.IWS_Almacen3")]
    public interface IWS_Almacen3
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_Almacen3/EjecutarCompra", ReplyAction="http://tempuri.org/IWS_Almacen3/EjecutarCompraResponse")]
        System.Threading.Tasks.Task<ServiceReferenceAlmacen3.RespuestaCompra> EjecutarCompraAsync(ServiceReferenceAlmacen3.CompraInfo compra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_Almacen3/ObtenerUltimas10Compras", ReplyAction="http://tempuri.org/IWS_Almacen3/ObtenerUltimas10ComprasResponse")]
        System.Threading.Tasks.Task<ServiceReferenceAlmacen3._10UltimasCompras[]> ObtenerUltimas10ComprasAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_Almacen3/ObtenerDetalleCompra", ReplyAction="http://tempuri.org/IWS_Almacen3/ObtenerDetalleCompraResponse")]
        System.Threading.Tasks.Task<ServiceReferenceAlmacen3.DetalleCompra> ObtenerDetalleCompraAsync(string numeroIngreso);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IWS_Almacen3Channel : ServiceReferenceAlmacen3.IWS_Almacen3, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WS_Almacen3Client : System.ServiceModel.ClientBase<ServiceReferenceAlmacen3.IWS_Almacen3>, ServiceReferenceAlmacen3.IWS_Almacen3
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WS_Almacen3Client() : 
                base(WS_Almacen3Client.GetDefaultBinding(), WS_Almacen3Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWS_Almacen3.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_Almacen3Client(EndpointConfiguration endpointConfiguration) : 
                base(WS_Almacen3Client.GetBindingForEndpoint(endpointConfiguration), WS_Almacen3Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_Almacen3Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WS_Almacen3Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_Almacen3Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WS_Almacen3Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_Almacen3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAlmacen3.RespuestaCompra> EjecutarCompraAsync(ServiceReferenceAlmacen3.CompraInfo compra)
        {
            return base.Channel.EjecutarCompraAsync(compra);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAlmacen3._10UltimasCompras[]> ObtenerUltimas10ComprasAsync(string filtro)
        {
            return base.Channel.ObtenerUltimas10ComprasAsync(filtro);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceAlmacen3.DetalleCompra> ObtenerDetalleCompraAsync(string numeroIngreso)
        {
            return base.Channel.ObtenerDetalleCompraAsync(numeroIngreso);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWS_Almacen3))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWS_Almacen3))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8089/WS_Almacen3.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WS_Almacen3Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWS_Almacen3);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WS_Almacen3Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWS_Almacen3);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWS_Almacen3,
        }
    }
}
