//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Proveedor", Namespace="http://schemas.datacontract.org/2004/07/WS_Almacen2.Models")]
    public partial class Proveedor : object
    {
        
        private string CedulaJuridicaField;
        
        private string CorreoElectronicoField;
        
        private bool EstadoField;
        
        private string NombreContactoField;
        
        private string NombreEmpresaField;
        
        private string TelefonoField;
        
        private string TipoTransaccionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CedulaJuridica
        {
            get
            {
                return this.CedulaJuridicaField;
            }
            set
            {
                this.CedulaJuridicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico
        {
            get
            {
                return this.CorreoElectronicoField;
            }
            set
            {
                this.CorreoElectronicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado
        {
            get 
            { 
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreContacto
        {
            get
            {
                return this.NombreContactoField;
            }
            set
            {
                this.NombreContactoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreEmpresa
        {
            get
            {
                return this.NombreEmpresaField;
            }
            set
            {
                this.NombreEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTransaccion
        {
            get
            {
                return this.TipoTransaccionField;
            }
            set
            {
                this.TipoTransaccionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaProveedor", Namespace="http://schemas.datacontract.org/2004/07/WS_Almacen2.Models")]
    public partial class RespuestaProveedor : object
    {
        
        private string MensajeField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IWS_Almacen2")]
    public interface IWS_Almacen2
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_Almacen2/MantenerProveedor", ReplyAction="http://tempuri.org/IWS_Almacen2/MantenerProveedorResponse")]
        System.Threading.Tasks.Task<ServiceReference2.RespuestaProveedor> MantenerProveedorAsync(ServiceReference2.Proveedor proveedor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_Almacen2/ListarProveedores", ReplyAction="http://tempuri.org/IWS_Almacen2/ListarProveedoresResponse")]
        System.Threading.Tasks.Task<ServiceReference2.Proveedor[]> ListarProveedoresAsync(string filtro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_Almacen2/CambiarEstadoProveedor", ReplyAction="http://tempuri.org/IWS_Almacen2/CambiarEstadoProveedorResponse")]
        System.Threading.Tasks.Task<ServiceReference2.RespuestaProveedor> CambiarEstadoProveedorAsync(string cedulaJuridica);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IWS_Almacen2Channel : ServiceReference2.IWS_Almacen2, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WS_Almacen2Client : System.ServiceModel.ClientBase<ServiceReference2.IWS_Almacen2>, ServiceReference2.IWS_Almacen2
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WS_Almacen2Client() : 
                base(WS_Almacen2Client.GetDefaultBinding(), WS_Almacen2Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IWS_Almacen2.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_Almacen2Client(EndpointConfiguration endpointConfiguration) : 
                base(WS_Almacen2Client.GetBindingForEndpoint(endpointConfiguration), WS_Almacen2Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_Almacen2Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WS_Almacen2Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_Almacen2Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WS_Almacen2Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_Almacen2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.RespuestaProveedor> MantenerProveedorAsync(ServiceReference2.Proveedor proveedor)
        {
            return base.Channel.MantenerProveedorAsync(proveedor);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.Proveedor[]> ListarProveedoresAsync(string filtro)
        {
            return base.Channel.ListarProveedoresAsync(filtro);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.RespuestaProveedor> CambiarEstadoProveedorAsync(string cedulaJuridica)
        {
            return base.Channel.CambiarEstadoProveedorAsync(cedulaJuridica);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWS_Almacen2))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IWS_Almacen2))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8089/WS_Almacen2.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WS_Almacen2Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IWS_Almacen2);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WS_Almacen2Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IWS_Almacen2);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IWS_Almacen2,
        }
    }
}
